# Generated by Django 3.1.3 on 2020-12-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legs', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('family', models.CharField(max_length=50)),
            ],
        ),
    ]
