# Generated by Django 3.1.4 on 2020-12-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0004_auto_20201209_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Work', 'Work'), ('Home', 'Home'), ('Studie', 'Studies'), ('Social', 'Social'), ('Shopping', 'Shopping')], default='Work', max_length=100),
        ),
    ]
