# Generated by Django 3.1.4 on 2020-12-18 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel', '0004_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='booking_ref',
        ),
        migrations.AddField(
            model_name='review',
            name='author',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
