# Generated by Django 3.1.4 on 2020-12-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='f1_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='f1_id',
            field=models.IntegerField(null=True),
        ),
    ]
