# Generated by Django 3.1.4 on 2020-12-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_post', '0004_driver_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='trade_status',
            field=models.BooleanField(default=False),
        ),
    ]
