# Generated by Django 3.1.4 on 2020-12-22 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading_post', '0005_card_trade_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('card1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_to_trade', to='trading_post.card')),
                ('card2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_card', to='trading_post.card')),
            ],
        ),
    ]
