# Generated by Django 3.1.4 on 2020-12-23 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading_post', '0008_auto_20201222_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='card1',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='card_to_trade', to='trading_post.card'),
            preserve_default=False,
        ),
    ]
