# Generated by Django 3.1.4 on 2020-12-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_post', '0009_auto_20201223_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
